# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mainnav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnav',
            name='imag',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
